### ISSUE TITLE
Removing search string does not reset search

### ISSUE THREAD

**Issue by TAKeanice** [ViennaRSS/vienna-rss#1120]
When typing a search string into the search field, the article list gets filtered properly.
However, when the small "x" button is used to delete the search string, or when deleting symbols from the string, the search is not reset (even after pressing enter).
After removing a search string, when a new letter is typed into the search field, after a short delay, the article list loads the filtered articles.

**Comment by TAKeanice** [comment]
Let me review that issue first

**Comment by Eitot** [comment]
I think I cam across this issue a while back. The problem is that Vienna doesn’t use the appropriate delegate action for the search field to respond to the cancel button. Instead of using delegate methods specific to NSSearchField, such as when cancelling using the cancel (x) button, it uses the delegate methods of NSTextField (superclass) to check whether whether txt has been entered or removed.

I think I have a commit somewhere, I will check this today.

**Comment by Eitot** [comment]
I managed to salvage [a small commit](https://github.com/Eitot/Vienna/tree/search-field) with some changes that at least fix the behaviour somewhat.

It needs further improvement:
- The underlying search mechanism seems to have no way to cancel a search. I opted to delete the search folder instead upon cancelling the search, but it needs some tweaking. Specifically, deleting the folder messes with the folder selection. It might be required to cache the previous folder selection and restore that one. 
- Search only works by pressing enter. It seems that the delegate callbacks are not that great, specifically it doesn’t seem that NSSearchFieldDelegate has methods to respond to changed queries, both callbacks are called exactly once: when the user starts typing in the search field once and when the search is cancelled (either by clicking the cancel button or by clearing the search field and pressing enter); there is no intermediate state.
