### ISSUE TITLE
Subscription URLs corrupted after in flight wifi

### ISSUE THREAD

**Issue by pait** [ViennaRSS/vienna-rss#1145]
I took a flight on JetBlue and now all my Feed URLs have been replaced by http://www.flyfi.com/index.htm?

Is there an easy way to revert, and to avoid this bug in the future?

**Comment by barijaona** [comment]
Unfortunately, I see no other solution than restoring the database from a backup.
Your problem reminds me of #380, which should have been fixed by #463 …
If you can describe more precisely the sequence of events and what you did, especially when you switched from one network to another, it would be helpful.

**Comment by pait** [comment]
Thanks! 

I didn't do much. Boarded a flight, saw there was free wifi, opened my computer to do something else. When I got back I saw that most (not all) of my subscriptions show flyfi as the URL in info.

I did restore from a version just before the flight, but the problem hasn't gone away. I cannot make much sense of it.

**Comment by barijaona** [comment]
What did you restore ?

**Comment by pait** [comment]
I redid the restore. Now I restored the complete ~/Library/Application Support/Vienna folder, and my subscriptions are back online. I think I had only restored Sources before, and that was not enough.

Thanks!

**Comment by barijaona** [comment]
You're welcome.
I will keep the issue open for a few days, in case some additional details can be found.

**Comment by pait** [comment]
Most excellent!
