### ISSUE TITLE
open link in background with external browser (chrome)

### ISSUE THREAD

**Issue by chrysler76** [ViennaRSS/vienna-rss#1174]
Opening links brings chrome in foreground.

**Comment by mattgrosso** [comment]
This appears to correlate to the most recent release of Chrome (Version 69.0.3497.100 (Official Build) (64-bit)) and is super annoying.

**Comment by barijaona** [comment]
This is unrelated to Vienna.

@lapcat [wrote](http://cocoaforge.com/viewtopic.php?f=18&t=27092#p140439) : 

> You can solve this by opening the URL chrome://flags/#views-browser-windows in Chrome and switching to Disabled.

**Comment by mattgrosso** [comment]
This seems to have cropped up again and the provided solution no longer seems available. Does anyone know if there is a solution for the most recent versions of Chrome (71.0.3578.98)?

**Comment by stevetranby** [comment]
None that I know of, but I've since switched to Safari as my default browser now. I still currently use Chrome for everything else, but I think I might give Firefox another try (since forever ago) and then use it as default into the future. 

This is definitely a Chrome/Chromium issue. If I had to guess it's actually intended whether for security or otherwise, but I do wish they'd have kept the flag option available. 

I suppose Vienna could have an option to try force itself on top & focused?
