### ISSUE TITLE
Apostrophes are exported as &apos;

### ISSUE THREAD

**Issue by bisherbas** [ViennaRSS/vienna-rss#1198]
https://github.com/ViennaRSS/vienna-rss/blob/2b555770756b4e56786d0078ef4982a9635cfe3f/Vienna/Sources/Shared/StringExtensions.m#L717

I don't understand much of this code but I see that the object linked above is responsible for converting `'` into `&apos;`. Is there any reason why that's the case?

I exported my feeds into the OPML file and some of my feeds had `'` in the title. When I imported the generated OPML file into another RSS reader, feed titles including `'` would display as `&apos;` as expected.

**Comment by barijaona** [comment]
Reminds me of #732 and probably requires just the same solution.
Problem appeared between Vienna 3.0 and Vienna 3.1, most likely due to the modernization of RichXML architecture (Pull Request #495)
Note that Vienna itself has [mechanisms to protect itself from such double escaping](https://github.com/ViennaRSS/vienna-rss/blob/master/Vienna/Sources/Database/Import.m#L96-L98 "Import.m"). Could be extended to description and not just text, though…

Your opinion, @josh64x2 ?
