### ISSUE TITLE
Don't check for new articles on startup broken

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#1394]
Vienna always checks for new articles on startup even when the preference is disabled.

**Comment by barijaona** [comment]
From my observations (through requests to allow access to Keychain), it's not "always". It's occasional on relaunches.

Try this experience:
- wait the scheduled refresh to occur
- quit the app and relaunch it

It this is done in a short time interval, the refresh does not occur immediately after the relaunch.

Since the switch to NSBackgroundActivityScheduler (#1311), the OS has some discretion regarding when the task is executed. Apparently, as the identifier of the scheduler is persistent, the system can "guess" if it's interesting or not to redo something it did recently…

**Comment by Eitot** [comment]
I did not come across any cross-launch persistence in the documentation. I wonder if it can be avoided by invalidating the refresh scheduler before quitting Vienna, e.g. in `-dealloc`.

**Comment by Eitot** [comment]
I wonder if it can be avoided by invalidating the refresh scheduler before quitting Vienna, e.g. in `-dealloc`.

**Comment by barijaona** [comment]
I think it's fine as it is : the "Check for new articles on start up" option is respected when it is activated. If it isn't, we have a "smart" timer.

I think we should change the default behavior : "Check for new articles on start up" should be unchecked on initial setup of the application.

**Comment by Eitot** [comment]
I think the forced refresh at startup should give the system a signal that a refresh happened, so that it does not call the refresh handler too soon after. It could be achieved by scheduling the activity immediately upon startup and then scheduling the regular one afterwards. I am also thinking that NSBackgroundActivityScheduler is likely better moved to RefreshManager.

I think that NSBackgroundActivityScheduler ties into [xpc/activity.h](https://developer.apple.com/documentation/xpc/activity_h) somehow, maybe it is even a wrapper for it. It does not seem to give any other options though.

**Comment by josh64x2** [comment]
This might actually be due to this option in my preferences which hasn't worked before (because I've never left Vienna open for 3 hours...)

![image](https://user-images.githubusercontent.com/799345/103060160-57f95d00-45fb-11eb-8ece-8e6bcc991fcf.png)

I'll keep an eye on it and see what happens.
