### ISSUE TITLE
Feed makes Vienna crash

### ISSUE THREAD

**Issue by TAKeanice** [ViennaRSS/vienna-rss#1448]
This is a follow-up to #1447
The feed https://home.solari.com/feed/ made Vienna crash.
We should investigate why it was able to do so.

**Comment by TAKeanice** [comment]
Possibly the feed is behind a paywall? And the login is not requested when accessing the site?

**Comment by TAKeanice** [comment]
https://www.bitchute.com/channel/solarireport/ is what's hiding behind the RSS symbol on top of the site

**Comment by jtieber** [comment]
| On Mar 9, 2021, at 12:17 PM, Tassilo Karge <notifications@github.com> wrote:

| Could you help us to investigate further @jtieber? See #1448

I’d be happy to help, but don’t know what else I can add.

I had 301 feeds; Vienna suddenly began crashing a few seconds after starting up. Initially I didn’t associate the crashing with refreshing (I’ve always had it set to refresh on starting). Tassilo suggested it was crashing only when refreshing, which turned out to be correct and, using Tassilo’s suggestion, I refreshed chunks of feeds until I identified and removed the Solari feed.

There’s been no problems since I deleted that feed.

**Comment by TAKeanice** [comment]
@jtieber As @Eitot said, there seems to be no feed address. Did you have a paid subscription for that site?

**Comment by jtieber** [comment]
> On Mar 9, 2021, at 9:49 PM, Tassilo Karge ***@***.***> wrote:
> 
> 
> @jtieber <https://github.com/jtieber> As @Eitot <https://github.com/Eitot> said, there seems to be no feed address. Did you have a paid subscription for that site?
> 
> 

No, I never did, nor am I certain that I ever received any posts from the site via that feed.
