### ISSUE TITLE
Layered customization with "ALL/ANY" of Smart Folders

### ISSUE THREAD

**Issue by sherlock440** [ViennaRSS/vienna-rss#1458]
I love Vienna as one of the few counted RSS clients that allow you to create customizable Smart Folders. But this option isn't exactly handy - the paid program ReadKit does it better (there it's done with Alt pressed while pressing the "+").

It's all about the ability to create multiple "layers" for the "All" and "Any" option. This is best illustrated by the example on the screenshot: the "All" rule is in the outer "layer", but there is another "Any" rule inside it.
![IMG_396BAFE60AC0-1](https://user-images.githubusercontent.com/63901545/118564115-68f86580-b778-11eb-83da-e2281804d997.jpeg)
In this example, it is done so that Smart Folder will display news that either contains the word "Durov" in its title or text (and not both at once), but will also save only unread news.

When this "layered" option is not available, I have to create many folders:

Smart Folder #1
**ALL:**
-- Read = No
-- Title = contains "Durov"

Smart Folder #2
**ALL:**
-- Read = No
-- Content = contains "Durov"

When there are only 2 rules, it's not so depressing. But if you have a lot of rules, then creating a separate Smart Folder for each of them is unrealistic - it's much easier to create a universal one:

Smart Folder | Telegram
**ALL:**
-- Read = No
-- **ANY:**
---- Title = contains "Durov"
---- Content = contains "Durov"
---- ... = ...

**Comment by xanoni** [comment]
I came here to submit exactly this. I'm new to Vienna and saw that by default there's a shortcut for "New Smart Folder", but not for "New Group Folder". Thus, I assumed that I'm supposed to use Smart Folders and that Group Folders are considered legacy. 

Alright, I felt ready for some change, but I failed at a very basic task. How can I create a folder that has all unread and undeleted messages that contain one of the following words in the subject OR body: privacy, security, osint.

![image](https://user-images.githubusercontent.com/77220130/121818778-38142f00-cc57-11eb-8a6e-d024b300d966.png)

Apparently not possible. Back to Dumb Folders for now.

**Comment by xanoni** [comment]
By the way, it would be great if we could just use some scripting language to write filters. Like in ProtonMail, where you can either use the UI to create filters, or if you have more advanced needs, then you can use the Sieve scripting language to create/update/extend your rules.

**Comment by TAKeanice** [comment]
I must say I really hate not being able to use full logic in Smart Folders, filters etc.. I am angry every time I try to filter my emails and can only select "all" (everything AND) or "any" of the conditions (everything OR). Guess I will make this the next project to work on in Vienna.

If any of you feel like some programming on their favorite news reader in their spare time, we're glad about any help!

**Comment by Eitot** [comment]
Apple has a native API for this filter UI called [NSPredicateEditor](https://developer.apple.com/documentation/appkit/nspredicateeditor). You can see it in action in Finder smart folders. Unfortunately, it is one of those older, obscure APIs for which there is little documentation by Apple. I think it supports this behaviour where you can create sub-filters by holding down the option key too, just like you can do in Finder.

It is not straightforward to adopt, since NSPredicateEditor is based upon the SQL-based NSPredicate syntax to combine the filters into a query. Vienna instead uses a custom XML-format to store the query in the database. It then converts that XML query into a different format for the database SQL queries. To maintain backwards compatibility, those XML-based queries would have to be translated/converted into the SQL-based NSPredicate format that Apple uses.

**Comment by TAKeanice** [comment]
I had a look at this some time ago but didn't find enough time to implement the change, but I still feel committed to doing it.

I am not sure if we should transfer existing smart folders to the new system though, since it would make the implementation more difficult. I'd rather reimplement the whole predicate system

**Comment by TAKeanice** [comment]
Isn't it possible to introduce custom operators by subclassing `NSPredicateEditorRowTemplate`? As far as I understand, it only has to return a high value in match(for:) to be chosen to display the compound not(like) predicate

**Comment by TAKeanice** [comment]
> but visually it is shown like a simple comparison template.

Exactly that. Simplifying the representation is enough, having it as a compound predicate in the model space is cleaner.

**Comment by TAKeanice** [comment]
I cannot see your feature branch, is it only local?

**Comment by TAKeanice** [comment]
Don't worry about test code, you can still force-push everything later! I would really like to look at it tonight (currently in Indonesia, so tonight starts in about 4h ;) )
