### ISSUE TITLE
broken url present in title when special chars are present such as "$;#@"

### ISSUE THREAD

**Issue by pirasterize** [ViennaRSS/vienna-rss#1462]
**Describe the bug**
If the article url contain special chars the clicked link present in the title is broken. It seems a encode/decode url problem 

**To Reproduce**
all articles presents in this flux https://ec.europa.eu/info/funding-tenders/opportunities/data/referenceData/grantTenders-rss.xml have the url broken

**Screenshots**
<img width="1039" alt="Capture d’écran 2021-06-17 à 11 23 50" src="https://user-images.githubusercontent.com/8769656/122370829-ae6aa700-cf5f-11eb-9df8-bb41ac843be5.png">

Version 3.7.1 :d356d926: (7437)
Mac OS 10.14.6 MOJAVE

**Comment by Eitot** [comment]
For reference:
```xml
<item>
  <title>Fostering balanced brain circulation – ERA Fellowships</title>
  <link>https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search;programCode=HORIZON;callCode=HORIZON-WIDERA-2022-TALENTS-04</link>
  <description>&lt;div&gt;&lt;b&gt;Identifier&lt;/b&gt;: HORIZON-WIDERA-2022-TALENTS-04&lt;br/&gt;&lt;b&gt;Pillar&lt;/b&gt;: Widening participation and spreading excellence&lt;br/&gt;&lt;b&gt;Planned Opening Date&lt;/b&gt;: &lt;br/&gt;&lt;b&gt;Deadline&lt;/b&gt;: Thu, 29 Sep 2022 17:00:00 (Brussels local time)&lt;br/&gt;&lt;/div&gt;
  </description>
  <category>HORIZON.4.1</category>
  <category />
  <pubDate>Tue, 15 Jun 2021 22:00:00 GMT</pubDate>
  <guid>https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search;programCode=HORIZON;callCode=HORIZON-WIDERA-2022-TALENTS-04</guid>
  <dc:date>2021-06-15T22:00:00Z</dc:date>
</item>
```

The problem seems to be specifically the semicolon in the URL.
```
https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search%3BprogramCode=HORIZON%3BcallCode=HORIZON-WIDERA-2022-TALENTS-04
```

The bug presents itself in the internal browser as well as when copying the URL in Vienna.

**Comment by Eitot** [comment]
The problem is this line:
```objc
NSURL *urlToLoad = [NSURLComponents componentsWithString:urlString].URL
```

NSURLComponents percent-encodes the semicolon in the `path` component when it returns the URL via the `URL` or `string` accessors. This is mentioned somewhere in the [documentation](https://developer.apple.com/documentation/foundation/nsurlcomponents/1408161-percentencodedpath) as well: 
> Although an unencoded semicolon is a valid character in a percent-encoded path, for compatibility with the NSURL class, you should always percent-encode it.

I do not think that the problem is in NSURLComponents specifically, but the way in which Vienna handles those percent-encoded URLs needs to changed. NSString has a `stringByRemovingPercentEncoding` property that should return the unencoded URL as a string.

**Comment by Eitot** [comment]
Just one more clarification: NSURLComponents does not percent-encode semicolons in the `query` part of the URL, where the semicolon is a substitute for the ampersand (`&`), e.g. `?key1=value&key2=value` or `?key1=value;key2=value`. The issue here pertains specifically to the `path` part of the URL (the part before the query). Safari has no problems with this, notwithstanding that it seems unusual for a URL to have a semicolon in the `path`.
