### ISSUE TITLE
Vienna crashes on refresh

### ISSUE THREAD

**Issue by ndryden** [ViennaRSS/vienna-rss#1662]
**Describe the bug**
Vienna crashes when refreshing all my feeds, either manually or on startup. Interestingly, if I manually refresh the feeds (with right click -> refresh selected subscriptions), it only crashes if I refresh too many at once. I have not added any new feeds recently; this started to occur yesterday. It does not crash immediately, and usually manages to successfully refresh a few feeds. If I manage to stop the refresh in time, Vienna works fine.

**To Reproduce**
All I have to do is refresh. I don't want to share my list of feeds, so this may be a bit vague.

**Screenshots**
n/a

**Please complete the following information:**
 - Vienna version: 3.8.5
 - OS version: 13.2.1

**Additional information:**
Attached is the stack trace/etc. from macOS's diagnostics: [vienna-crash.txt](https://github.com/ViennaRSS/vienna-rss/files/10897643/vienna-crash.txt)

**Comment by pukku** [comment]
I ran into this recently, and was able to narrow it down to one feed that was causing the problem. (I have my feeds organized into folders, and was able to stop it refreshing at start up, and then go folder by folder, then feed by feed within the crashing folder.)

The issue I ran into was some feed had changed host, and probably because they were still putting together the website, they stopped having a feed at the same path. They had updated something so that Vienna knew about the new host, but the feed URL was was responding with a 403 error, which seemed to be causing the crash. Since this was a feed that hadn't been updated in years anyway, and I was no longer interested in it, I just unsubscribed.

So it's possible that the issue is with the feed changing, not with anything on your end.

(I admit, Vienna probably shouldn't just crash like that because of a 403 or something, but you might be able to isolate the feed in question (or I suppose feeds if you have multiple from the same host) and get more details that way?)

**Comment by ndryden** [comment]
I was able to individually refresh every feed without a crash, hence my guess that it had something to do with initiating many refreshes at once. When refreshing groups of feeds, I could not determine a specific threshold that caused the crash, and I did see crashes when refreshing disjoint sets of feeds.

However, this issue seems to have gone away a day ago without me making any changes to the feeds I'm subscribed to, so I'm unfortunately not sure I can provide additional information to help isolate this. :/ (Feel free to close unless there's another lead on this.)
