### ISSUE TITLE
updated dates taking precendence over published even when setting is turned off

### ISSUE THREAD

**Issue by minusf** [ViennaRSS/vienna-rss#1749]
**Describe the bug**
`updated` dates taking precendence over `published` even when setting is turned off

**To Reproduce**
1. `Mark updated articles as new` setting turned off, set order by date descdencing
2. get a youtube feed
3. get updated content sorted in front of later published content.

**Screenshots**

xml to test: https://www.youtube.com/feeds/videos.xml?playlist_id=UULF21uZkfXpT8rPY-gPgMiCwA

<img width="343" alt="Screenshot 2024-05-06 at 17 40 44" src="https://github.com/ViennaRSS/vienna-rss/assets/3632883/512e37a3-6ac5-435f-b93d-51b0e144f5c3">

**Please complete the following information:**
 - Vienna version 3.9.0 :7ad9df044: (8175)
 - OS version: 14.4.1

**Additional information:**
In which version of Vienna does the problem not occur, if applicable.

**Comment by barijaona** [comment]
I acknowledge the problem.
RSS specifications do not differentiate between publication date and modification/update date.
Atom and JSON Feed specifications have the distinction, but Vienna's architecture hasn't changed to handle the distinction. Vienna just takes the most recent date, which is likely to be the `<updated>` date.

I am undecided on what to do: is the distinction important enough to justify an increase of database size?

**Comment by TAKeanice** [comment]
I think one additional date value can't hurt any proper database

**Comment by minusf** [comment]
Some creators go back and keep changing their content. It is debatable if this should result in bumping the content to the front again, but for exactly this reason if the RSS feed provides the distinction, the app should too...

**Comment by barijaona** [comment]
> I think one additional date value can't hurt any proper database

It's not just an additional field in the database, I am also thinking about how this should affect the user interface.

In fact, since 2006 😱 (commit [ad60f21](https://github.com/ViennaRSS/vienna-rss/commit/ad60f210bffaf4ed0a74c00ff30384599bbe61de#diff-73137d0bf68e3d0342326a196e2a1a954ccb0e83c2a073c1af92d9ec787d616b) for version 2.1.0), the `messages` table includes a `createddate` field, but this is barely used and its only impact for end users is the existence of the "Last Refresh" filter.

Let's take an analogy : since OS X, Apple's filesystem handles multiple dates for files : creation date, date added, last modification date, last access date…
However, for a long time, Apple's Finder only displayed the 'last modification' date. As far as I remember, display of the other dates or use of them for sorting has been added relatively recently and these features are only discreetly put forth in the user interface.

In my opinion, Vienna's philosophy is similar to Apple's one : hide complexity as much as possible.
I am therefore tempted to add a "sort by created date" option, but continue to display only the "last update date" in the article list. Apart from the "keep it simple and stupid" philosophy, there are other reasons behind this:
- the specifications for some kind of feeds do not distinguish between creation date / last update date
- article list with vertical layout risks being overcrowded

**Comment by barijaona** [comment]
Closed in 3.9.4
