### ISSUE TITLE
Allow dock icon to be hidden

### ISSUE THREAD

**Issue by natebrunette** [ViennaRSS/vienna-rss#292]
Add configuration for hiding dock icon if icon is showing in menu bar.

**Comment by barijaona** [comment]
Attached is a patch that allows hiding the Dock.

[issue292-HideDock.patch.zip](https://github.com/ViennaRSS/vienna-rss/files/190691/issue292-HideDock.patch.zip)

It is still a bit crude and unfinished ; after applying the patch, you'll have to type a terminal command to hide the Dock icon. Make sure that you enable the "_Show in menu bar_" preference before, otherwise you will be unable to get access to the application !

    defaults write uk.co.opencommunity.vienna2 "LaunchAsAgentApp" 1



To reactivate the Dock, type : 

    defaults delete  uk.co.opencommunity.vienna2 "LaunchAsAgentApp"

My personal opinion is that this feature is a bit too geeky to be included in the standard.
