### ISSUE TITLE
add 'current articles' to application properties

### ISSUE THREAD

**Issue by LucaFilipozzi** [ViennaRSS/vienna-rss#440]
As a developer of AppleScript scripts, I want to iterate over the potentially multiple articles selected by the user.

**Comment by josh64x2** [comment]
Related to #387

**Comment by garwood** [comment]
I, too, would prefer this to be native AppleScript functionality. In my experience, acting upon the set of selected articles is a common dēsīderātum. Ultimately, what's the point of being able to select multiple articles if one can not then act upon that set of articles?

I'd suggest that syntax such as 'selected articles' or 'articles whose selected is true' would be clearer than the proposed 'current articles'. It appears to me that: multiple articles may be selected; only one article can be current (it's the one displayed in the preview/render pane). Any article in table may be selected, current, both, or neither. 

So, I'd propose:
&nbsp;&nbsp;&nbsp;&nbsp; all sets '{ }' may contain { &empty; .. &infin; article(s) };
&nbsp;&nbsp;&nbsp;&nbsp; 'articles' := { all articles in table }; 
&nbsp;&nbsp;&nbsp;&nbsp; 'selected articles' := { articles whose attribute select is true }; 
&nbsp;&nbsp;&nbsp;&nbsp; 'flagged articles' := { articles whose attribute flag is true }; 
&nbsp;&nbsp;&nbsp;&nbsp; 'read articles' := { articles whose attribute read is true }; 
&nbsp;&nbsp;&nbsp;&nbsp; 'deleted articles' := { articles whose attribute delete is true }; 
&nbsp;&nbsp;&nbsp;&nbsp; 'current article' := &empty; | one article that is currently displayed in the preview pane. 

Nonetheless, I can make do with whatever selector syntax is made available. 

Since the original request for this functionality was made circa 2015 and has not yet been fulfilled, it would appear to be a low priority. (Not a complaint, just an observation.)

As a work-around, I've developed (and personally use) a method to emulate this functionality with GUI scripting. While GUI scripting is annoyingly brittle compared to native AppleScript functionality, we work with what we have.

The meaty bits of an AppleScript method to work with multiple article selection follow.

```applescript
tell application "System Events"
	tell process "Vienna"
		activate
		tell first table of first scroll area of first splitter group of first group of first splitter group of first window
			set selectedRows to rows whose (value of attribute "AXSelected") is true
			if (selectedRows is not "") then
				repeat with targetRow in selectedRows
					select targetRow
					tell application "Vienna"
						set the_article to current article
						try
							-- process the_article
						end try
					end tell								
				end repeat
			end if
		end tell
	end tell
end tell
```
