### ISSUE TITLE
OpenReader (Inoreader): HTTP code 403 reported from server

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#456]
All of my feeds disappeared this morning, and I haven't been able to refresh them.  In the activity window for each feed, I get an error:

    Connecting to Open Reader server to retrieve http://url.com/feed
    HTTP code 403 reported from server

I tried restoring the `Application Support/Venna` directory from Time Machine and refreshing again, but get the same results.  Is this an indication of a problem on InoReader's end, or some problem with Vienna?  When I look at the [InoReader docs](https://www.inoreader.com/developers/error-handling), it says 403 means `You are not sending the correct AppID and/or AppSecret`.

**Comment by barijaona** [comment]
I confirm the problem with my own test account.

From May 1st, InoReader requires an application ID and application secret. http://blog.inoreader.com/2015/02/introducing-new-inoreader-developer.html

Sorry, I was unaware of this change. I will work on it in the next few days. I cannot make a commitment on a delivery day though, because I will be in a location with difficult access to the Internet.

**Comment by tonycpsu** [comment]
OK, I'm glad it's being worked on.

**Comment by ehemmete** [comment]
Thank you! It was driving me crazy trying to figure out why I couldn't connect to InoReader.  Looking forward to the fix!

**Comment by explorersupport** [comment]
https://safaribrowser001.deviantart.com/ great post [https://safaribrowser001.deviantart.com/](url)
