### ISSUE TITLE
Space wasted in filter bar

### ISSUE THREAD

**Issue by miguelarauj1o** [ViennaRSS/vienna-rss#469]
Much of the search bar is being wasted (left side). On the other hand, if the feed has a huge description, part thereof is 'cut' from the search bar (right side). 

See image below.
<img width="313" alt="screenshot 2015-07-29 11 13 36" src="https://cloud.githubusercontent.com/assets/7546651/8959983/078204da-35e4-11e5-8966-8c777f359dd6.png">

**Comment by josh64x2** [comment]
@miguelarauj1o what layout are you using? I can't reproduce this :frowning:

**Comment by Echelon9** [comment]
I can confirm this on my setup with default view and filter bar active.

OS X 10.10 using latest Vienna 3.0.6.

**Comment by barijaona** [comment]
I also see the problem. Might be a centered alignment problem.

**Comment by miguelarauj1o** [comment]
@josh64x2, horizontal. OS X 10.10.4 using latest Vienna 3.0.6.

**Comment by jonahb** [comment]
I looked into this. The issue is that the NSSearchField does not perform layout when its cell's placeholder string is changed, which happens when a new folder is selected.

I was thinking this could be solved by simply calling `setNeedsLayout` on the search field, but, unfortunately, NSSearchField animates its contents when it loses focus, so `setNeedsLayout` causes a visual hiccup.

I think this will be tricky to solve given the public interface to NSSearchField. A workaround would be to have the filter field simply read "Filter," like the search fields in Finder, Mail, etc.

**Comment by josh64x2** [comment]
So weird. I still can't reproduce this and my search fields in Finder and Mail both say "Search" not "Filter".
:confused:

**Comment by jonahb** [comment]
Right, the Finder and Mail search fields say "Search." I just meant that you could use a single word ("Filter") that doesn't change with the search scope.

To repro, show the filter bar, then select a folder/feed with a short name, then one with a long name.

**Comment by josh64x2** [comment]
Ahh excellent, thanks!
