### ISSUE TITLE
Preview/Message List Divider Creep

### ISSUE THREAD

**Issue by arjay67** [ViennaRSS/vienna-rss#523]
I've been having a recurring issue with the divider between the message list and the preview pane. I will drag it to where I want it and it stays. It will stay in that place when quitting Vienna and relaunching. But at some point in the next few days, it will revert back to it's stock position and I have to drag it back to where I would like it. I haven't noticed any specific number of restarts that will cause it to revert.

**Comment by josh64x2** [comment]
@arjay67 are you using the horizontal or the vertical layout? Which versions of Vienna and OS X is this on?

Thanks!

**Comment by arjay67** [comment]
Vienna 3.0.8 :074a131:
OSX 10.11 (El Capitan)
Horizontal layout

**Comment by josh64x2** [comment]
OK thanks, I will try to investigate.

**Comment by dak180** [comment]
@josh64x2 in my experience it seems most likely to revert (or otherwise change position) after crashing or being closed as part of os shutdown / reboot.

**Comment by ehlers** [comment]
Vienna 3.0.9 :22b3ce2:, OS X 10.11.2, Horizontal layout

Same problem, on every close the divider goes down about half a line. I have this issue since a long time, I started to live with it.

Here the initial layout
![layout-initial](https://cloud.githubusercontent.com/assets/896406/12990068/80ba16d4-d108-11e5-8ba4-e4e04f7259ba.png)

And here the layout after several quits (cmd Q) and new starts:
The divider has moved down 4 1/2 lines
![layout-later](https://cloud.githubusercontent.com/assets/896406/12990093/a97f9c2e-d108-11e5-9d2b-46fdef07d1b3.png)

**Comment by josh64x2** [comment]
@ehlers when you quit vienna does it close straight away or does it pause for a few seconds before closing?

**Comment by ehlers** [comment]
It closes immediately, no delay between cmd-Q and the termination of the program.

**Comment by ehlers** [comment]
Just updated from 3.0.9 to 3.1.3 and the issue is gone.

**Comment by barijaona** [comment]
I have no idea of what caused this or what solved it. I’ll close the issue though.

**Comment by mwhdc** [comment]
This issue remains in 3.7.1 (7437) under Big Sur 11.4 and I have just learned to live with it, but if it could be eliminated, I would be grateful.

In horizontal layout, the divider bar creeps down about the height of a line of text (i.e., one feed article), every time the app is quit (Cmd-Q) and restarted. Eventually the preview pane reaches zero height and the divider has to be dragged back up.
