### ISSUE TITLE
Fix delay when quitting Vienna

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#529]
When quitting Vienna a beachball will appear and Vienna takes a few seconds to quit.
Need to investigate cause.

**Comment by josh64x2** [comment]
This delay appears to be from `[Database isTrashEmpty]` being called when terminating the application.

**Comment by barijaona** [comment]
How about adding an index on messages (deleted_flag) ?

**Comment by Eitot** [comment]
I have done some testing on a massive database. I placed signposts in Database's `-purgeDeletedArticles` method. The database took 1,38 seconds to complete the SQLite `DELETE` statement, 28,19 seconds to complete `VACUUM` and less than a second to clear the cache (Folder `-clearCache`).

I looked into solutions and found that SQLite supports `auto-vacuum` mode, that reclaims space upon `DELETE` statements. Here I found that on the same database (backed up before to replicate the results), the `DELETE` statement took 2,66 seconds and reduced the space by almost the same amount as `DELETE` and `VACUUM` combined did, without requiring a `VACUUM` just to empty Trash.

Some downsides:
- Enabling `auto-vacuum` requires a manual `VACUUM` to rebuild the database with that setting enabled (can be acceptable if done as part of a database migration). For new users, it can be enabled upon database creation.
- The [documentation](https://www.sqlite.org/pragma.html#pragma_auto_vacuum) states that `auto-vacuum` can result in less-efficient use of paging and worse fragmentation, without explaining what the results can be. This might be mitigated by letting the user call `VACUUM` manually to address any issues (similar to database reindexation).
- It is not clear to me whether `auto-vacuum` has performance penalties in other database operations. A mitigation might be `incremental` mode rather than `full` mode and call `PRAGMA incremental_vacuum` on specific statements (e.g. `DELETE`).

**Comment by Eitot** [comment]
I did some testing of my own using `os_signpost` and came across the following results: [`purgeDeletedArticles`](https://github.com/ViennaRSS/vienna-rss/blob/d7de37245e780e7bdfc7546047f781ad1156137a/Vienna/Sources/Database/Database.m#L1682-L1697) overall took about 30 seconds to complete; 1,38 seconds of which for the `DELETE` statement, 28,19 seconds for the `VACUUM` statement and less than a second for cache removal (Folder `-clearCache`). I performed the test on a test database with 353.156 messages, 52.443 of which were marked as deleted. The result was a space reduction from 1,44 GB to 1,29 GB.

I did some reading on the `VACUUM` statement and found this [blog post](https://blogs.gnome.org/jnelson/2015/01/06/sqlite-vacuum-and-auto_vacuum/) insightful. `VACUUM` is an expensive operation, both in terms of space usage and time to complete, while Vienna is completely unresponsive. Based on the blog post, there is no easy way around the fact that `VACUUM` has to lock the entire database for its duration and that it cannot do it in chunks, meaning that putting this into a background queue will not be possible.

It appears that SQLite supports a `auto_vacuum` mode that reclaims space immediately (like reference counting is to garbage collection). This mode either does it automatically using the `full` mode, or semi-automatically using the `incremental` mode. I found that on the test database (a pristine copy) the `DELETE` statement took about 2,66 seconds and managed to reduce the space to 1,29 GB as well, _without_ using `VACUUM`. This means that this change alone can improve the performance significantly, while giving some of the benefits of `VACUUM` at the same time.

There are some downsides:
- `auto_vacuum` can lead to increased page usage. I suppose this means that space usage might become less efficient and cause performance penalties. However, I have not come across any concrete downsides to this. These problems can be resolved by using `VACUUM`, maybe as an option to the user.
- The `auto_vacuum` flag has to be set upon table creation or before a VACUUM operation. For existing databases, there is no quick transition. This can be done as part of a database migration.
- It is not clear to me, whether `auto_vacuum = FULL` has performance penalties on other database operations. The mode `auto_vacuum = INCREMENTAL` gives more control, but requires a `PRAGMA incremental_vacuum` statement to work.

I have a test implementation at https://github.com/Eitot/Vienna/tree/database.
