### ISSUE TITLE
Extreme slowness to delete series of articles

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#650]
As reported here : http://forums.cocoaforge.com/viewtopic.php?f=18&t=26837

**Comment by josh64x2** [comment]
@barijaona I did some profiling in Instruments (which wasn't a lot of fun because it changed since last time I used it!!), and it looks like our old friend the NSCache is responsible somehow. 
![screen shot 2016-05-19 at 10 17 17](https://cloud.githubusercontent.com/assets/799345/15378919/1a189118-1dab-11e6-9ca3-09bee6f1a13f.png)

Looks like the cache function gets called for each article being deleted. Do you think that could cause the slowness?

**Comment by barijaona** [comment]
Yes, the cache is descontructing/reconstructing itself a lot during the process.
I hope to submit a fix by tomorrow.
