### ISSUE TITLE
Feedly?

### ISSUE THREAD

**Issue by mwoffenden** [ViennaRSS/vienna-rss#741]
Since there seems to be no way to search issues here by content...

Is anyone working on Feedly integration?

**Comment by barijaona** [comment]
I had a look at it a long time ago, but Feedly seemed too different of other servers to be worth the effort.

**Comment by kylegoetz** [comment]
This would be nice to have. Feedly is a free, very high-quality (no other RSS app on Android looks as nice in my experience) mobile app and has free syncing to their servers, which means if Vienna could support it, it would work as a quasi-cross-device solution that is beautiful on OSX (with Vienna) and Android (with Feedly), and I don't know anything about iOS to say one way or the other.

I could look at implementing this myself, but I haven't coded in C (Vienna appears to be C) since the 90s and that was just for one course in high school, same with C++, and couldn't test the implementation since Xcode takes up many lottabytes of disk space that my laptop does not have :/

I'm in the middle of developing an Android app to act as a front end for Miniflux just so I can have a cross-platform RSS reader solution, but boy howdy would it be nice to keep using Feedly and Vienna instead.
