### ISSUE TITLE
Scaling/display problem with Vienna 3.18

### ISSUE THREAD

**Issue by smurffff** [ViennaRSS/vienna-rss#751]
I'm running MacOS 10.9.5, using the "Unified" layout and the "Feedlight Graphite" theme from version 3.09 (since I don't like the font the 3.18 version uses for the articles).

When I open Vienna, the right pane of the window, where the articles show, is not scaled properly. I mean the contents of the window are much too wide for the window, so that horizontal scrolling would be required to read the articles.

If I resize the window to make it super super wide, and then resize it again back to the proper size, the contents of the window scale correctly, and continue to be ok as long as Vienna is running. But when I quit & reopen Vienna, the scaling problem returns.

This problem does not exist in Vienna 3.09. When I open that version of Vienna, the articles pane is scaled correctly without me having to do anything.

**Comment by josh64x2** [comment]
Thanks for this report, I'll look into it.

**Comment by josh64x2** [comment]
@Eitot any ideas what might cause this?

**Comment by Eitot** [comment]
I’ll have a look. Has anyone been able to reproduce this?

**Comment by Eitot** [comment]
Coincidentally, the problem is likely related. I see that the unified layout is based on a table view as well. The table rows are stretching beyond the ‘natural’ size of the table view, causing the scroll view to draw a larger canvas. It is good to know that this problem existed before Auto Layout, the problem thus might be elsewhere.
