### ISSUE TITLE
Implementation of Activity window might be improved

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#866]
As discovered with @josh64x2 while discussing #864 : on current `master`, if Activity Window is opened before a feed refresh, it just remains blank.

You can check that by disabling "Check new articles on startup" in Preferences ; relaunch Vienna, then open Activity Window and refresh feeds.

On examining code, I also noticed that some notifications are emitted but not handled : `activityItemStatusUpdatedNotification`and `activityLogUpdatedNotification`.

@Eitot, could you have a look at situation post #832 ?

**Comment by Eitot** [comment]
There is a missing KVO notification. The table is not updated when an item is inserted. Not sure what to do about the initial fetch though. The reason why I made the changes is to get rid of unnecessary coupling between the classes.

**Comment by barijaona** [comment]
> Not sure what to do about the initial fetch though.

How about setting ActivityPanelController's `activityLog` on first item insertion instead of [on window loading](https://github.com/ViennaRSS/vienna-rss/blob/master/src/ActivityPanelController.m#L52-L53) ?

**Comment by josh64x2** [comment]
This should all be handled by the NSArrayController binding in the xib file. I'll have a look at it tonight if I have time.

**Comment by Eitot** [comment]
I am just not happy with the design of the activity log. It seems to me that it has architectural problems throughout. Instead of inserting or updating objects in the `allItems` array directly, GoogleReader et al. retrieve a single ActivityItem using `-itemByName:`, then update its properties. ActivityItem itself then sends a notification when a property is changed. What happens is this:

1. ActivityLog creates an empty array.
2. GoogleReader et al. request an ActivityItem from ActivityLog using `-itemByName:`.
3. `-itemByName:` either retrieves an existing item or creates a new one and adds it to the array.
4. GoogleReader et al. update the properties of ActivityItem (_after_ the item was added to the array).
5. ActivityItem sends a notification when a property changes.
6. Either ActivityLog or ActivityPanelController respond to these notifications.

Worse still, when a feed is removed, Database sends a notification to ActivityLog, which then in turn simply removes the corresponding ActivityItem from the array. I believe this model is complicated and fragile. It doesn’t work with Cocoa bindings, because the array is not properly updated. Once this done, all that is left is sending KVO notifications, allowing the table to update itself.

I think we should get rid of `-itemByName:`. Perhaps a better approach would be a method on ActivityLog that creates/updates values directly in the array. Ideally, ActivityItem should not be used in GoogleReader at all. I am thinking along the lines of value types here. Perhaps I should give it a try with Swift.

**Comment by barijaona** [comment]
Yes, give it a try.
As PR #872 and #875 have been submitted for a week now and have no known issue, I will merge #875 now so you will have a stable GoogleReader as a basis of your work.

**Comment by barijaona** [comment]
@Eitot, is it possible for you to give us a feedback regarding your work on this during the next week ?

As I said, I prefer `master` to include an average (but reversible) solution than having no solution at all. So, if your work will take time, I would merge #876 and submit the improved workaround for #833.

**Comment by Eitot** [comment]
I will try out several solutions in the next couple of days. I did have a KVO-based solution ready that seems to work as well.

I think one of the problems is ActivityLog itself. It makes little sense to have it being created and then live on as a singleton, even if the user may never open the activity log in the first place. This is the reason why the panel is not populated when the window first opens.

It would be better if we simply record the changes in the database instead and then have ActivityPanelController retrieve that data.

**Comment by barijaona** [comment]
Personnally, I’d feel safer with transient informations not being stored in the database itself.

**Comment by josh64x2** [comment]
Sorry everyone, I am on vacation until the 23rd May so I have limited availability.
I guess we need to decide what functionality we want from the Activity log and what the original intent was.

1. Is it meant to keep a record of everything that has happened since Vienna was opened for that session?
2. Is it meant to aid in debugging Vienna at all?
3. Is the activity log meant to persist in event of crash?
4. If i open the activity viewer, close it, and then open it again, do I expect the previous activity to still be visible in the activity viewer?

**Comment by barijaona** [comment]
> 
> Is it meant to keep a record of everything that has happened since Vienna was opened for that session?
No, it is meant to keep track of what has happened during last refresh
> Is it meant to aid in debugging Vienna at all?
It is not intended for debugging Vienna, it is intended to help you debug your subscription list ; especially, understanding feeds in error or feeds which are not refreshing.
> Is the activity log meant to persist in event of crash?
No.

> If i open the activity viewer, close it, and then open it again, do I expect the previous activity to still be visible in the activity viewer?
Yes, the previous information should remain visible while no new refresh attempt has occurred.

**Comment by Eitot** [comment]
The log does seem to have one other purpose: show how much has been fetched since the last time.

> Yes, the previous information should remain visible while no new refresh attempt has occurred.

What if the user chooses not the fetch at startup or has no Internet connection before the first fetch occurred? Why should that information not be there after a restart? The user ought to expect that the application is resumed as much as possible nowadays.

> it is intended to help you debug your subscription list ; especially, understanding feeds in error or feeds which are not refreshing.

Vienna already shows failures in the sidebar, just like Mail. Could we not transform the activity log into something like Mail’s Connection Doctor that examines a feed on-demand? We can always log additional data to Console in the event the user wants to examine real-time information.

**Comment by barijaona** [comment]
> What if the user chooses not the fetch at startup or has no Internet connection before the first fetch occurred? Why should that information not be there after a restart? The user ought to expect that the application is resumed as much as possible nowadays.
> 
I would then expect to have some date informations, because connection settings and location could have changed since last refresh attempt, especially when using a notebook
> Vienna already shows failures in the sidebar, just like Mail. Could we not transform the activity log into something like Mail’s Connection Doctor that examines a feed on-demand? We can always log additional data to Console in the event the user wants to examine real-time information.
> 
Console is not user friendly at all.
The sidebar icon is helpful to warn you that there is a problem, but is not sufficient to understand what is the nature of the problem : connection / authentication / XML parsing / 404…
I’d appreciate infos currently seen in Activity window to be available through feed’s Info window.
