### ISSUE TITLE
XML source window

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#893]
The XML source window doesn't seem to behave that well. Depending on the size of the file, it can be a bit unresponsive when it loads and when the user scrolls. It also doesn't necessarily present the format in a readable manner, as it makes almost no changes to the layout, such as by adding indentations or line breaks, or remove superfluous whitespace, to improve readability. I also don't find the WebView- and JavaScript-based implementation very elegant and it looks like security precautions are needed against unwanted JavaScript injections (which begs the question why it should be done this way to begin with).

I'll ask bluntly: do we actually need this? For debugging purposes (parsing errors) it would suffice to just check out the file in the library. There is also the external validation option in the Get Info window that the user could use instead. Moreover, if we do add JSON support, then this window would have to be improved too with JSON-specific logic and another syntax highlighter.

**Comment by pukku** [comment]
I like being able to see what Vienna is operating on. I have a few times been able to identify an issue with a feed causing Vienna to not parse things properly by using the XML Source window. (I think at least once it was because there was an HTML5 video tag, without the tailing '/', in the source of the article, which therefore made it invalid XML.)

That being said, what I actually want is just to know what exactly Vienna thinks the current feed data is. I don't need the syntax highlighting, etc. I usually copy the data into a text browser to actually look at it.

I'm not sure what you mean by "check out the file in the library". Also the few times I've tried the "external validation", it hasn't been useful -- it doesn't tell me what Vienna thinks the data is, only what the validation service retrieves (and what it considers valid).

**Comment by Eitot** [comment]
A copy of the XML file is stored in the user library at ~/Library/Application Support/Vienna/Sources. The XML window is basically just a viewer for this file, with some [minor text replacements](https://github.com/ViennaRSS/vienna-rss/blob/master/src/XMLSourceWindow.m#L80-L86). For the most part it just prints the raw source as retrieved from the server and adds syntax highlighting.

Malformed or invalid XML should be spotted by the validator service, this isn't something the XML source window is particularly useful for, unless the syntax highlighter shows it. We could look for a substitute service if the current one is not working satisfactorily. From what I can see it doesn't look as though Vienna does anything else to the source when it retrieves and saves the copy. Perhaps we could substitute the source window with a "Show in Finder" button to show the location of the XML file instead. I am of course open to other suggestions too.

I wouldn't mind expanding the functionality of the source window, but I wonder if it were fruitful to spend time on this. Removing it would get rid of some code in AppController, which is a priority at the moment.

**Comment by cixonline** [comment]
XML Source was added because when the parser was being written, the number of edge cases was huge and resolving them not only required users to send me the source but often I had to forward them to the site owner to fix the generation on their side. It doesn't really need to be on the popup menu though. A button on the Info page would be easier.

- Steve

**Comment by josh64x2** [comment]
I think it would be fine to remove the XML Source window for now, and maybe just have a button on the info page as Steve suggested, but the button can "Show in Finder" the XML file in `~/Library/Application Support/Vienna/Sources`.

**Comment by Eitot** [comment]
The window has been removed. Instead, a button can now be found in the Info window where the user can open the file in their default XML handler (or TextEdit).

We should reconsider this in the future if we have some more time to spend on refactors/improvements.
