### ISSUE TITLE
Renaming feeds/folders looks awful

### ISSUE THREAD

**Issue by DavidMunch** [ViennaRSS/vienna-rss#929]
Renaming feeds and folders produce an editing field overlay with a different font size, instead of editing the name inline. It looks pretty bad. :)

![viennarenaming](https://user-images.githubusercontent.com/3511519/27760772-a37a9fe2-5e4f-11e7-89b1-5a04af8c98f7.jpg)

Vienna 3.1.10, but not a new issue.

**Comment by josh64x2** [comment]
There will be a PR for this soon.

**Comment by DavidMunch** [comment]
Still an issue.

**Comment by nivivier** [comment]
Experiencing this issue as well :)

**Comment by barijaona** [comment]
On macOS 11, it looks correct with light appearance but it is still awful with dark appearance.

@DavidMunch and @nivivier , which version of macOS do you use ?

**Comment by josh64x2** [comment]
@barijaona - @Eitot and myself have made good progress on using view based cells for the whole feed list. We are waiting for the WebKit branch to merge before we finish it off and then it will fix this issue.

**Comment by nivivier** [comment]
I am on 10.15. It looks like you narrowed it down well @barijaona :
- Light mode : when starting to rename, the item cell background changes to white, covering the old name, then the new text we type is readable
- Dark mode : the cell background remains transparent, leaving the old name visible which makes this text-on-text issue, making it impossible to read what we type in.

**Comment by DavidMunch** [comment]
> On macOS 11, it looks correct with light appearance but it is still awful with dark appearance.
> 
> @DavidMunch and @nivivier , which version of macOS do you use ?

Vienna 3.7.1 on macOS 11.1 - Both newest releases.
I see the issue with both in light and dark mode.

![Screenshot 2021-02-01 kl  21 09 19](https://user-images.githubusercontent.com/3511519/106512498-fbc70a00-64d1-11eb-948e-c3c522361b5a.jpg)
![Screenshot 2021-02-01 kl  21 09 46](https://user-images.githubusercontent.com/3511519/106512500-fcf83700-64d1-11eb-8c00-1facf9e7cf09.jpg)

**Comment by Eitot** [comment]
It admittedly looks bad, but at least it is still functional. In any case, there is work-in-progress branch for modern sidebar style, but it needs to wait until the WebKit stuff is merged, since both touch the same Interface Builder files. There are some issues that still need to be resolved though.

**Comment by Eitot** [comment]
It admittedly looks bad, but at least it is still functional. In any case, there is a work-in-progress branch for a modern sidebar style, but it needs to wait until the WebKit stuff is merged, since both touch the same Interface Builder files. There are some issues that still need to be resolved though.
