### ISSUE TITLE
Weird behavior of criteria menu

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#944]
When one tries to edit a smart folder, duplicate or blank choices appear for criterias applicable to some types of data (date, subject)
<img width="697" alt="vienna__2862_unread_" src="https://user-images.githubusercontent.com/442030/28242010-499ed596-69a9-11e7-8f02-73061fdef66c.png">

**Comment by Eitot** [comment]
I cannot reproduce this on `legacy`.

**Comment by josh64x2** [comment]
Yeah, looks to only be an issue on `master`

**Comment by Eitot** [comment]
This bug may also be causing this error:
> DB Error: 1 "no such column: KEYWORD"
> DB Query: select message_id, folder_id, parent_id, read_flag, marked_flag, deleted_flag, title, sender, link, createddate, date, text, revised_flag, hasenclosure_flag, enclosure from messages where (title=KEYWORD)

![screen shot 2017-07-21 at 17 32 54](https://user-images.githubusercontent.com/15073177/28470654-aa959e4e-6e3a-11e7-8827-6515b6ac900d.png)

**Comment by barijaona** [comment]
My debugging showed a parsing problem with `va_arg(arguments, NSUInteger)` in SearchFolder.
I included a workaround in #953.

**Comment by lapcat** [comment]
I believe the issue is that the operators are passed as long ints, but the 0 terminator is passed as an int. va_arg is always expecting a long int, and it can get garbage when it hits the 0 terminator because of the different type widths. It's best to avoid va_arg entirely. I've committed a fix in https://github.com/ViennaRSS/vienna-rss/pull/996/commits/ca66cd425d1ad0ee1ffd9e4dbbc3e1ec0fb4a8ec
