### ISSUE TITLE
Unread mark not updating when reading an article

### ISSUE THREAD

**Issue by nemoyatpeace** [ViennaRSS/vienna-rss#999]
I've been using Vienna for a while as my RSS reader, but a couple of months ago, this started happening, I figured it was a bug that would get fixed in an update, but it hasn't been fixed yet, so I figured I'd share.

Notice how in this image I have 6 messages in my unread folder, but 2 of them are read.  Yet the matching subscriptions have a total of 6 still marked unread.  I've actually already read all of those messages in the unread folder earlier today.  When I read them, they will lose the bold unread font, but the blue bubble doesn't change.  If I minimize the app and come back to it later, they will be bold again.

  The only way I've been able to get messages to be marked as unread forever is to close Vienna and reopen it, then if I read my messages in the next couple minutes they will be permanently marked as read.  This results in me having to restart Vienna any time I want to clear my unread messages.

These pictures are taken in succession:

1. I've read 2 of the messages.  <img width="875" alt="screen shot 2017-09-07 at 7 33 10 pm" src="https://user-images.githubusercontent.com/6550021/30161568-b0d54e28-9403-11e7-87d3-26d475f419b7.png">

2. Now I've read all of them.  <img width="1022" alt="screen shot 2017-09-07 at 7 44 39 pm" src="https://user-images.githubusercontent.com/6550021/30161883-10bbeed6-9405-11e7-9356-8572f38946db.png">

3. I selected a different folder and came back to the unread folder and they are all bold again.  <img width="1063" alt="screen shot 2017-09-07 at 7 45 48 pm" src="https://user-images.githubusercontent.com/6550021/30161922-2fcf29be-9405-11e7-9a15-f837758ff948.png">

Again, note how in all cases, the blue bubbles with unread count didn't change on the subscriptions.

Vienna version:
Version 3.1.12 :627f6323:

macOS Sierra
Version 10.12.5 (16F73)

**Comment by lapcat** [comment]
I'm not able to reproduce this issue. Anyone else?

**Comment by nemoyatpeace** [comment]
So, I just assumed this was the same for all.  Any thoughts on what more information I can give to help you recreate it?  I'm still having the issue.  I just restarted Vienna to clear 4 more "unread" messages that I'd already read.

**Comment by barijaona** [comment]
Did you try 3.1.13 and reindexing database ?

**Comment by nemoyatpeace** [comment]
I did update to 3.1.13, but haven't had any new feeds to test since then.  Not sure what reindexing database means.

**Comment by DavidMunch** [comment]
I've often seen the problem with read counts being wrong, where a restart of Vienna would always solve it. I haven't seen the read articles becomming unread bug though.

I sync with Bazqux, so I assumed it was a syncing problem, but I guess it could be a database issue. I should emphasize that I haven't seen wrong read counts for a while, so I assumed it had been fixed, but again, it could be a database issue which solved it self I guess?

**Comment by nemoyatpeace** [comment]
Nope, just read 2 more new posts.  Switched folders, then back to unread folder and they are marked unread again.  Reindexing does nothing.

**Comment by phiw13** [comment]
I’ve seen that quite a few times, and *on my side* it happens quite randomly. Read,  or mark an article as read while inside a *smart folder*. The article count does not change, but the article is seemingly marked read. Now go the actually feed for that site, and press `Cmd-K` (mark all as read). Watch the article count change, but the individual articles as still marked unread. Then click on each article, they are now marked read.

It certainly does not happen for all feeds. I haven’t found a pattern either. I’m fairly sure that feeds from Blogspot sites are immune to this issue. Ditto for feeds from Github. One site that regularly is victim of this bug is the Vienna forum feed. Others, hmm. Some Wordpress sites, e.g the iTunes guy: [Kirksville](https://www.kirkville.com/feed/) either self hosted or hosted by Wordpress. But Wordpress sites that use Feedburner and similar do not have a problem, I think (hard to say, as the issue happens randomly).

PS - similar thread in the [Vienna forum](https://forums.cocoaforge.com/viewtopic.php?f=18&t=26932).

**Comment by barijaona** [comment]
Version 3.1.16 _might_ make things better.

**Comment by nemoyatpeace** [comment]
Just installed the new version.  Will let you know in a few days...

Danny Whittaker

HS Math Teacher

International Community School (Singapore)

27A Jubilee Road, Singapore 128575

+65 6776-7435 | www.ics.edu.sg

**Comment by phiw13** [comment]
@barijaona [comment](https://github.com/ViennaRSS/vienna-rss/issues/999#issuecomment-332048007)

3.1.6 has been up and running for quite a few hours, and so far I have **not** experienced this issue. It is still early though, a number of feeds that are prone to suffer from this problem haven’t had any new articles yet.

**Comment by phiw13** [comment]
So after more than a week of monitoring: the situation has seriously improved, in that I have **much** less occurrences of this issue. A couple of feeds still are stubborn (e.g. Smashing magazine - feed: www.smashingmagazine.com/feed/), and only when marking “read” from within a smart folder.

(and again - issue happens randomly only).

**Comment by nemoyatpeace** [comment]
Agreed, it is better, but still an issue.

-- 
Danny Whittaker
HS Math Teacher

International Community School (Singapore)
27A Jubilee Road, Singapore 128575
+65 6776-7435 | www.ics.edu.sg

-----Original Message-----
Re: [ViennaRSS/vienna-rss] Unread mark not updating when reading an article
(#999)

**Comment by Iritscen** [comment]
Experiencing this problem all the time in 3.1.16.  The unread count for a feed will not decrease or clear when all its items are read (which I fix by saying "Mark All Articles As Read").

Also, articles (both read and unread) are randomly disappearing from the feed when a refresh happens.  Manually refreshing sometimes brings back the articles.  I wouldn't normally combine two issues under one bug report, but these seem to be related, because they didn't seem to happen at all until I updated to 3.1.16.  Vienna is almost unuseable for me now, so I'll try backtracking to an earlier release.

I'm in macOS 10.12.6, btw.

**Comment by DavidMunch** [comment]
I'll add this here, because I assume it is related - Vienna *sometimes* doesn't display all articles that it has, even though it is aware they are there according to the number of unread articles. Refreshing subscriptions doesn't fix the problem, but a restart of Vienna always does:

Before restart:
![skaermbillede 2018-06-05 kl 13 56 11](https://user-images.githubusercontent.com/3511519/40974765-e29b0430-68c8-11e8-9d12-90ad9afc5424.jpg)

After restart:
![skaermbillede 2018-06-05 kl 13 56 28](https://user-images.githubusercontent.com/3511519/40974770-e8a36584-68c8-11e8-8b04-64fcd2fed99e.jpg)

And regarding the unread state coming back, as described in the original post, I have now experienced it several times. But it is my clear understanding that in my case it is an issue with my Open Reader Server, Bazqux.com, because I observe it also with Feeddler on iOS, and on Bazqux.com itself if I have only read certain feeds there, so logically it has to be at the source, i.e. Bazqux. @nemoyatpeace do you use an ORS, or only local saved feeds?
